### ISSUE TITLE
Fix fonts to pass FontBakery

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Unna#5]
There's quite a few errors which will need fixing before we can push this family.

## Fontbakery report

Fontbakery version: 0.5.1.dev28+g39c4540c

<details>
<summary><b>[2] Family checks</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Check font has a license.</summary>

* [com.google.fonts/check/028](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/028)
* :fire: **FAIL** No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which is fine, just make sure there is a temporary license file in the same folder. [code: no-license]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have consistent underline thickness?</summary>

* [com.google.fonts/check/008](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/008)
* :fire: **FAIL** Thickness of the underline is not the same accross this family. In order to fix this, please make sure that the underlineThickness value is the same in the 'post' table of all of this family font files.
Detected underlineThickness values are:
	/Users/marc/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/Unna-Bold.ttf: 50
	/Users/marc/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/Unna-BoldItalic.ttf: 50
	/Users/marc/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/Unna-Italic.ttf: 35
	/Users/marc/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/Unna-Light.ttf: 28
	/Users/marc/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/Unna-LightItalic.ttf: 28
	/Users/marc/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/Unna-Medium.ttf: 42
	/Users/marc/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/Unna-MediumItalic.ttf: 42
	/Users/marc/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/Unna-Regular.ttf: 35

</details>
<br>
</details>
<details>
<summary><b>[5] Unna-Bold.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/011](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/011)
* :fire: **FAIL** Bold has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Light has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Medium has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Regular has 844 glyphs while BoldItalic has 852 glyphs.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/012](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/012)
* :fire: **FAIL** Glyphname 'ycircumflex.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'fi.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'j.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ydieresis.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ygrave.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'yacute.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'y.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'f.ss02' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* :fire: **FAIL** MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}

</details>
<details>
<summary>:fire: <b>FAIL:</b> Description strings in the name table must not contain copyright info.</summary>

* [com.google.fonts/check/031](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/031)
* :fire: **FAIL** Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

</details>
<br>
</details>
<details>
<summary><b>[5] Unna-BoldItalic.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/011](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/011)
* :fire: **FAIL** Bold has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Light has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Medium has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Regular has 844 glyphs while BoldItalic has 852 glyphs.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/012](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/012)
* :fire: **FAIL** Glyphname 'ycircumflex.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'fi.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'j.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ydieresis.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ygrave.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'yacute.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'y.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'f.ss02' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* :fire: **FAIL** MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 447, 448, 449, 452, 482, 503, 514, 515, 614, 616, 619, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 634, 655]}

</details>
<details>
<summary>:fire: <b>FAIL:</b> Description strings in the name table must not contain copyright info.</summary>

* [com.google.fonts/check/031](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/031)
* :fire: **FAIL** Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

</details>
<br>
</details>
<details>
<summary><b>[5] Unna-Italic.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/011](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/011)
* :fire: **FAIL** Bold has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Light has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Medium has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Regular has 844 glyphs while BoldItalic has 852 glyphs.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/012](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/012)
* :fire: **FAIL** Glyphname 'ycircumflex.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'fi.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'j.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ydieresis.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ygrave.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'yacute.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'y.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'f.ss02' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* :fire: **FAIL** MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 447, 448, 449, 452, 482, 503, 514, 515, 614, 616, 619, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 634, 655]}

</details>
<details>
<summary>:fire: <b>FAIL:</b> Description strings in the name table must not contain copyright info.</summary>

* [com.google.fonts/check/031](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/031)
* :fire: **FAIL** Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

</details>
<br>
</details>
<details>
<summary><b>[5] Unna-Light.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/011](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/011)
* :fire: **FAIL** Bold has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Light has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Medium has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Regular has 844 glyphs while BoldItalic has 852 glyphs.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/012](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/012)
* :fire: **FAIL** Glyphname 'ycircumflex.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'fi.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'j.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ydieresis.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ygrave.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'yacute.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'y.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'f.ss02' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* :fire: **FAIL** MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 388, 402, 411, 440, 441, 442, 445, 450, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 647, 719, 721, 759, 760, 809, 810, 811, 812, 813, 814, 815, 816, 825, 826]}

</details>
<details>
<summary>:fire: <b>FAIL:</b> Description strings in the name table must not contain copyright info.</summary>

* [com.google.fonts/check/031](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/031)
* :fire: **FAIL** Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

</details>
<br>
</details>
<details>
<summary><b>[9] Unna-LightItalic.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/011](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/011)
* :fire: **FAIL** Bold has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Light has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Medium has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Regular has 844 glyphs while BoldItalic has 852 glyphs.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/012](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/012)
* :fire: **FAIL** Glyphname 'ycircumflex.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'fi.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'j.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ydieresis.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ygrave.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'yacute.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'y.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'f.ss02' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 fsSelection value.</summary>

* [com.google.fonts/check/129](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/129)
* :fire: **FAIL** OS/2 fsSelection REGULAR bit should be reset. [code: bad-REGULAR]
* :fire: **FAIL** OS/2 fsSelection ITALIC bit should be set. [code: bad-ITALIC]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking head.macStyle value.</summary>

* [com.google.fonts/check/131](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/131)
* :fire: **FAIL** head macStyle ITALIC bit should be set. [code: bad-ITALIC]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Check name table: FONT_FAMILY_NAME entries. </summary>

* [com.google.fonts/check/157](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/157)
* :fire: **FAIL** Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the 'name' table: Expected 'Unna Light' but got 'Unna Light Italic'.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Check name table: FONT_SUBFAMILY_NAME entries. </summary>

* [com.google.fonts/check/158](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/158)
* :fire: **FAIL** Entry [FONT_SUBFAMILY_NAME(2):WINDOWS(3)] on the 'name' table: Expected 'Italic' but got 'Regular'. [code: bad-familyname]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* :fire: **FAIL** MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 447, 448, 449, 452, 458, 482, 503, 514, 515, 614, 616, 619, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 655, 797]}
* :fire: **FAIL** MS-FonVal: The macStyle italic bit is clear, but the post table italic angle is nonzero
* :fire: **FAIL** MS-FonVal: The italicAngle is nonzero, but the head.macStyle italic bit is not set

</details>
<details>
<summary>:fire: <b>FAIL:</b> Description strings in the name table must not contain copyright info.</summary>

* [com.google.fonts/check/031](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/031)
* :fire: **FAIL** Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

</details>
<br>
</details>
<details>
<summary><b>[5] Unna-Medium.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/011](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/011)
* :fire: **FAIL** Bold has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Light has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Medium has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Regular has 844 glyphs while BoldItalic has 852 glyphs.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/012](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/012)
* :fire: **FAIL** Glyphname 'ycircumflex.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'fi.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'j.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ydieresis.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ygrave.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'yacute.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'y.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'f.ss02' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* :fire: **FAIL** MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}

</details>
<details>
<summary>:fire: <b>FAIL:</b> Description strings in the name table must not contain copyright info.</summary>

* [com.google.fonts/check/031](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/031)
* :fire: **FAIL** Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

</details>
<br>
</details>
<details>
<summary><b>[9] Unna-MediumItalic.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/011](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/011)
* :fire: **FAIL** Bold has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Light has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Medium has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Regular has 844 glyphs while BoldItalic has 852 glyphs.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/012](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/012)
* :fire: **FAIL** Glyphname 'ycircumflex.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'fi.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'j.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ydieresis.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ygrave.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'yacute.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'y.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'f.ss02' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 fsSelection value.</summary>

* [com.google.fonts/check/129](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/129)
* :fire: **FAIL** OS/2 fsSelection REGULAR bit should be reset. [code: bad-REGULAR]
* :fire: **FAIL** OS/2 fsSelection ITALIC bit should be set. [code: bad-ITALIC]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking head.macStyle value.</summary>

* [com.google.fonts/check/131](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/131)
* :fire: **FAIL** head macStyle ITALIC bit should be set. [code: bad-ITALIC]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Check name table: FONT_FAMILY_NAME entries. </summary>

* [com.google.fonts/check/157](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/157)
* :fire: **FAIL** Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the 'name' table: Expected 'Unna Medium' but got 'Unna Medium Italic'.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Check name table: FONT_SUBFAMILY_NAME entries. </summary>

* [com.google.fonts/check/158](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/158)
* :fire: **FAIL** Entry [FONT_SUBFAMILY_NAME(2):WINDOWS(3)] on the 'name' table: Expected 'Italic' but got 'Regular'. [code: bad-familyname]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* :fire: **FAIL** MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 447, 448, 449, 452, 482, 503, 514, 515, 614, 616, 619, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 634, 655]}
* :fire: **FAIL** MS-FonVal: The macStyle italic bit is clear, but the post table italic angle is nonzero
* :fire: **FAIL** MS-FonVal: The italicAngle is nonzero, but the head.macStyle italic bit is not set

</details>
<details>
<summary>:fire: <b>FAIL:</b> Description strings in the name table must not contain copyright info.</summary>

* [com.google.fonts/check/031](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/031)
* :fire: **FAIL** Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

</details>
<br>
</details>
<details>
<summary><b>[5] Unna-Regular.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/011](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/011)
* :fire: **FAIL** Bold has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Light has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Medium has 844 glyphs while BoldItalic has 852 glyphs.
* :fire: **FAIL** Regular has 844 glyphs while BoldItalic has 852 glyphs.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/012](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/012)
* :fire: **FAIL** Glyphname 'ycircumflex.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'fi.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'j.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ydieresis.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'ygrave.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'yacute.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'y.ss01' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.
* :fire: **FAIL** Glyphname 'f.ss02' is defined on BoldItalic, Italic, LightItalic, MediumItalic but is missing on Bold, Light, Medium, Regular.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* :fire: **FAIL** MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}

</details>
<details>
<summary>:fire: <b>FAIL:</b> Description strings in the name table must not contain copyright info.</summary>

* [com.google.fonts/check/031](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/031)
* :fire: **FAIL** Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 50 | 50 | 343 | 57 | 427 |
| 0% | 5% | 5% | 37% | 6% | 46% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**

Please ignore the fails for License, glyph names and equal glyphs. These are false positives.

**Comment by Omnibus-Type** [comment]
Fixed

**Comment by m4rc1e** [comment]
This hasn't been fixed.

You still have issues with the winAscent, name records and glyphs with intersecting contours.

```
   Checking OS/2 usWinAscent & usWinDescent.
 * FAIL: OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

   Result: FAIL

>> com.google.fonts/check/040 with (('font[1]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-BoldItalic.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent.
 * FAIL: OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

   Result: FAIL

>> com.google.fonts/check/040 with (('font[2]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Italic.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent.
 * FAIL: OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

   Result: FAIL

>> com.google.fonts/check/040 with (('font[3]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Light.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent.
 * FAIL: OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

   Result: FAIL

>> com.google.fonts/check/129 with (('font[4]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-LightItalic.ttf'),)
   Checking OS/2 fsSelection value.
 * FAIL: OS/2 fsSelection REGULAR bit should be reset. [code: bad-REGULAR]
 * FAIL: OS/2 fsSelection ITALIC bit should be set. [code: bad-ITALIC]

   Result: FAIL

>> com.google.fonts/check/131 with (('font[4]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-LightItalic.ttf'),)
   Checking head.macStyle value.
 * FAIL: head macStyle ITALIC bit should be set. [code: bad-ITALIC]

   Result: FAIL

>> com.google.fonts/check/157 with (('font[4]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-LightItalic.ttf'),)
   Check name table: FONT_FAMILY_NAME entries.
 * FAIL: Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the 'name' table: Expected 'Unna Light' but got 'Unna Light Italic'.

   Result: FAIL

>> com.google.fonts/check/158 with (('font[4]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-LightItalic.ttf'),)
   Check name table: FONT_SUBFAMILY_NAME entries.
 * FAIL: Entry [FONT_SUBFAMILY_NAME(2):WINDOWS(3)] on the 'name' table: Expected 'Italic' but got 'Regular'. [code: bad-familyname]

   Result: FAIL

>> com.google.fonts/check/040 with (('font[4]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-LightItalic.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent.
 * FAIL: OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

   Result: FAIL

>> com.google.fonts/check/040 with (('font[5]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Medium.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent.
 * FAIL: OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

   Result: FAIL

>> com.google.fonts/check/129 with (('font[6]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-MediumItalic.ttf'),)
   Checking OS/2 fsSelection value.
 * FAIL: OS/2 fsSelection REGULAR bit should be reset. [code: bad-REGULAR]
 * FAIL: OS/2 fsSelection ITALIC bit should be set. [code: bad-ITALIC]

   Result: FAIL

>> com.google.fonts/check/131 with (('font[6]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-MediumItalic.ttf'),)
   Checking head.macStyle value.
 * FAIL: head macStyle ITALIC bit should be set. [code: bad-ITALIC]

   Result: FAIL

>> com.google.fonts/check/157 with (('font[6]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-MediumItalic.ttf'),)
   Check name table: FONT_FAMILY_NAME entries.
 * FAIL: Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the 'name' table: Expected 'Unna Medium' but got 'Unna Medium Italic'.

   Result: FAIL

>> com.google.fonts/check/158 with (('font[6]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-MediumItalic.ttf'),)
   Check name table: FONT_SUBFAMILY_NAME entries.
 * FAIL: Entry [FONT_SUBFAMILY_NAME(2):WINDOWS(3)] on the 'name' table: Expected 'Italic' but got 'Regular'. [code: bad-familyname]

   Result: FAIL

>> com.google.fonts/check/040 with (('font[6]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-MediumItalic.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent.
 * FAIL: OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

   Result: FAIL

>> com.google.fonts/check/040 with (('font[7]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Regular.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent.
 * FAIL: OS/2.usWinAscent value should be equal or greater than 1023, but got 883 instead [code: ascent]

   Result: FAIL

>> com.google.fonts/check/037 with (('font[0]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Bold.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}

   Result: FAIL

>> com.google.fonts/check/037 with (('font[1]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-BoldItalic.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}

   Result: FAIL

>> com.google.fonts/check/037 with (('font[2]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Italic.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}

   Result: FAIL

>> com.google.fonts/check/037 with (('font[3]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Light.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 388, 402, 411, 440, 441, 442, 445, 450, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 647, 719, 721, 759, 760, 809, 810, 811, 812, 813, 814, 815, 816, 825, 826]}

   Result: FAIL

>> com.google.fonts/check/037 with (('font[4]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-LightItalic.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 450, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 647, 789]}
 * FAIL: MS-FonVal: The macStyle italic bit is clear, but the post table italic angle is nonzero
 * FAIL: MS-FonVal: The italicAngle is nonzero, but the head.macStyle italic bit is not set

   Result: FAIL

>> com.google.fonts/check/037 with (('font[5]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Medium.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}

   Result: FAIL

>> com.google.fonts/check/037 with (('font[6]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-MediumItalic.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}
 * FAIL: MS-FonVal: The macStyle italic bit is clear, but the post table italic angle is nonzero
 * FAIL: MS-FonVal: The italicAngle is nonzero, but the head.macStyle italic bit is not set

   Result: FAIL

>> com.google.fonts/check/037 with (('font[7]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Regular.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: Intersecting contours DETAILS: {'Glyph index': [26, 36, 41, 63, 73, 90, 103, 110, 111, 131, 140, 141, 148, 158, 162, 165, 184, 193, 243, 253, 259, 279, 283, 286, 290, 308, 322, 329, 330, 350, 359, 360, 364, 377, 383, 385, 402, 411, 440, 441, 442, 445, 474, 495, 506, 507, 606, 608, 611, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 647]}

   Result: FAIL

>> com.google.fonts/check/008
   Fonts have consistent underline thickness?
 * FAIL: Thickness of the underline is not the same accross this family. In order to fix this, please make sure that the underlineThickness value is the same in the 'post' table of all of this family font files.
Detected underlineThickness values are:
	/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Bold.ttf: 50
	/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-BoldItalic.ttf: 50
	/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Italic.ttf: 35
	/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Light.ttf: 28
	/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-LightItalic.ttf: 28
	/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Medium.ttf: 42
	/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-MediumItalic.ttf: 42
	/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Regular.ttf: 35


   Result: FAIL

>> com.google.fonts/check/031 with (('font[0]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Bold.ttf'),)
   Description strings in the name table must not contain copyright info.
 * FAIL: Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

   Result: FAIL

>> com.google.fonts/check/031 with (('font[1]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-BoldItalic.ttf'),)
   Description strings in the name table must not contain copyright info.
 * FAIL: Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

   Result: FAIL

>> com.google.fonts/check/031 with (('font[2]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Italic.ttf'),)
   Description strings in the name table must not contain copyright info.
 * FAIL: Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

   Result: FAIL

>> com.google.fonts/check/031 with (('font[3]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Light.ttf'),)
   Description strings in the name table must not contain copyright info.
 * FAIL: Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

   Result: FAIL

>> com.google.fonts/check/031 with (('font[4]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-LightItalic.ttf'),)
   Description strings in the name table must not contain copyright info.
 * FAIL: Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

   Result: FAIL

>> com.google.fonts/check/031 with (('font[5]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Medium.ttf'),)
   Description strings in the name table must not contain copyright info.
 * FAIL: Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

   Result: FAIL

>> com.google.fonts/check/031 with (('font[6]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-MediumItalic.ttf'),)
   Description strings in the name table must not contain copyright info.
 * FAIL: Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

   Result: FAIL

>> com.google.fonts/check/031 with (('font[7]', '/var/folders/f7/2dqpt71s6f7b91z7_vbgykkm0000gn/T/tmp1q1_5k8_/Unna-Regular.ttf'),)
   Description strings in the name table must not contain copyright info.
 * FAIL: Namerecords with ID=10 (NameID.DESCRIPTION) should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.)

   Result: FAIL

```
